### ISSUE TITLE
可以更进一步

### ISSUE THREAD

**Issue by ssrsec** [l3yx/Choccy#3]
可以将ql的lib那几个语言的ql单独拿出来，改改中文啥的，刚好跟自定义规则能够放一起，方便维护

**Comment by l3yx** [comment]
官方库的规则是随着codeql引擎一起更新迭代的，两者版本差异过大还可能有兼容性问题。所以暂不计划对官方规则进行任何额外修改和维护。不过目前的【查询套件】功能是可以同时圈选官方规则和自定义规则的，从逻辑上将两者"放在一起"：

```
- description: test

- queries: .
  from: codeql/java-queries
- include: 
    id:
    - java/command-line-injection

- qlpack: choccy/java
```
<img width="1458" alt="image" src="https://github.com/l3yx/Choccy/assets/42339081/d7ec102f-9127-4c71-b824-b7537d27ec41">
